### ISSUE TITLE
Random softlocks on 3.68 with mods

### ISSUE THREAD

**Issue by ShrineFox** [dots-tb/rePatch-reDux0#14]
I am not sure if this is related to issues #7 and #9 but I figure it's worth mentioning anyway.
I've tested with both PCSG01030 and PCSG01031 and eventually after a modded file is loaded, other assets will stop loading and the game will hang on the next loading screen. I have noticed this happen even if the game isn't suspended. Doesn't seem like it's an issue on 3.60. 🤔

**Comment by dots-tb** [comment]
#7

**Comment by ShrineFox** [comment]
I don't think this is an issue with suspending the game, though. Just seems like a general memory leak. Just to clarify, you're aware of other issues unrelated to that with 3.68?

**Comment by Ranomez** [comment]
Personally I have played the games I patch with rePatch for long periods of time, in fact I once played Digimon World Next Order for 4h straight and never encountered that issue unless I either put the console in sleep mode or go to the LiveArea, since you're saying it happens to you even if you don't suspend the games I have to ask if you are sure you didn't maybe do either of those by accident and forgot after?

**Comment by dots-tb** [comment]
If the new update does not work, I will reopen.
