### ISSUE TITLE
Pre-Release rePatch Issues

### ISSUE THREAD

**Issue by dots-tb** [dots-tb/rePatch-reDux0#15]
Please post them here. Thanks.

**Comment by kylon** [comment]
enso 3.60,  rePatch 2.71

random reboots (no errors, no gpu crash) when booting untouched games (no rePatch overlay), they seem to be working fine after that

random C2-xxxxx errors when booting a rePatched game for the first time after a reboot

random crashes: exception: unknown cause, thread name: Unity_Startup, cause: 0x00010005, SceLibc

**Comment by dots-tb** [comment]
Thanks for the information @kylon

**Comment by CelesteBlue-dev** [comment]
@kylon please I need : TITLE ID of the game, title of the game, exact error code

**Comment by kylon** [comment]
these things are random, these are the ones that i could get to crash/reboot

(game + update - untouched)
xenon valkyrie+ PCSE01191 - reboot
AW vs SAO PCSE01071 - reboot
YS VIII PCSB01128 - reboot

(game + update - repatched)
Sky Force Anniversary PCSB00826 - crash, error C2-12828-1, attached 15327260xx

All these games are working, i mean, if you reboot, the system goes back to normal, sky force boots just fine, xenon etc.. give an error

i attached all the logs, old and sky force, but i don t remember the game for the others, i hope they can help somehow

[crashlogs.zip](https://github.com/dots-tb/rePatch-reDux0/files/2237352/crashlogs.zip)

**Comment by dots-tb** [comment]
For future reference, I've added information for getting debug information:
https://github.com/dots-tb/rePatch-reDux0/wiki/Debug-Info-for-Bugs-and-Modding

**Comment by kylon** [comment]
repatch debug + shiplog, the system is stuck on molecule logo and led blinking :\

**Comment by kylon** [comment]
here is the log for AW vs SAO reboot
[logger.txt](https://github.com/dots-tb/rePatch-reDux0/files/2247286/logger.txt)

**Comment by ZayedHegazi** [comment]
(Game ID : PCSE00903)

I cannot load my save file if the DLC is installed since it displays a message that says "cannot load the DLC data properly" once I use any version of Repatch that is after Repatch 1.0 . And if I start a new game, the DLC costumes make the character invisible, many have posted about this issue on the subreddit sadly. I have to revert back the first version of Repatch to make the game work :/

The DLC is legit , rePatch solely used for patching Persona 4 Golden and not DLC modding. The problem was present since I was on 3.65 but persisted till 3.68.

**Comment by OperationNT414C** [comment]
**FW version:** 3.65 with Enso
**Application:** Package Installer
**Other plugin loaded:** "iduSpoof.suprx" (only for title ID NPXS10031)
**Symptom:** Violent system reboot

Unfortunatly, the "iduSpoof.suprx" plugin source cannot be found anymore because it was done by SilicaAndPina who has close its github. Here is the plugin binary: [iduSpoof.zip](https://github.com/dots-tb/rePatch-reDux0/files/2333615/iduSpoof.zip)
