### ISSUE TITLE
[Dumb Request] ur0 support

### ISSUE THREAD

**Issue by Lykie** [dots-tb/rePatch-reDux0#32]
I can fit Puyo Puyo Tetris into imc0 if I remove the unnecessary Japanese files, and the English patch fits perfectly on ur0.

**Comment by dots-tb** [comment]
Hi! I was told that ur0 support was a bad idea because we are suppose to discourage writing to ur0 as its non-replaceable. But devices can be added very easily by adding them to this list: 
https://github.com/dots-tb/rePatch-reDux0/blob/master/repatch.h#L91 

If you want a custom build, I can provide one.

**Comment by Lykie** [comment]
I know that writing to ur0 is a bad idea, but I figured it'd be worth asking since Adrenaline has support for it.

The custom build would be helpful, TIA.

**Comment by dots-tb** [comment]
[repatch.zip](https://github.com/dots-tb/rePatch-reDux0/files/2602079/repatch.zip)
@Lykie
