### ISSUE TITLE
work on 3.68?

### ISSUE THREAD

**Issue by SilicaAndPina** [dots-tb/rePatch-reDux0#7]
*im sorry*

**Comment by devingDev** [comment]
are u tho

**Comment by dots-tb** [comment]
the suspend issue might return in 3.68

**Comment by engagexes** [comment]
Working good so far the issue i confront either stuck in splash screen (senran kagura ev mod) but that can be fixed by deleting any file except tpk folder, now there are problem I'm not sure how to fix, sometimes the games will stuck on loading screen (sk sv, sk ev, Gundam breaker 3(decrypted dlc)) , im sorry for posting my problem here

Btw  by fw is 3.68

**Comment by mtrj1776** [comment]
Not working for me on 3.68. followed everything i can find on the internet related to installing rePatch. Will not translated to games i have tried so far (pso2 nova and pso2).

Does seem to access rePatch folder correctly, if i patch eboot with vitashell, it will load vitashell instead of game.

Game loads but with no patch from rePatch folder applied.

Pulling my hair out currently! Please help. Thanks!

**Comment by RikuNoctis** [comment]
I can confirm that the suspend issue is present on 3.67 and 3.68, while on 3.65 it does not (I have 3 Vitas).
The patch for Phantasy Star Nova works, and I can play as much as I want without crashes until I go to Livearea, or suspend my Vita. I noticed this first when going to Livearea, as I don't usually suspend it.
I can also confirm that on both 3.67 and 3.68 the reAddcont folder works with DLC (same game), so this is probably just the same issue as the one before rePatch Redux, but for the newest firmwares.
